core.simtPeCount=2
cube.l0b_buffer_entry_width=2048
core.cube_core_num=4
tmu.dual_pe_ring_mode=true
tmu.ring_node_num=16
tmu.cube_read_port=0:1:2:3
tmu.cube_write_port=4:5:6:7
tmu.mtc_read_port=2
tmu.mtc_write_port=3
tmu.bcc_port=8
tmu.vec_read_port=8:9:10:11
tmu.vec_write_port=12:13
tmu.tma_read_port=14:16
tmu.tma_write_port=15:17