[TEST_CASE_1]
command = path_to_gfsim/gfsim -m 10 -s core.soc_enable=true core.bp_mode=0 core.perfect_load_store=false -s core.simtEnable=false -f /remote/lms06/modelci/jenkins/workspace/files_root/benchmark_ckpt/pkgs/ckpt-v0.50.2-2000w20k-0704.zip.d/ckpt-v0.50.2-2000w20k-0704/spec2006/400.perlbench/400.perlbench-llvm-ckpt/400.perlbench-20250705-12104.json
description = test_case_1

[TEST_CASE_2]
command = path_to_gfsim/gfsim -m 10 -s core.soc_enable=true core.bp_mode=0 core.perfect_load_store=false -s core.simtEnable=false -f /remote/lms06/modelci/jenkins/workspace/files_root/benchmark_ckpt/pkgs/ckpt-v0.50.2-2000w20k-0704.zip.d/ckpt-v0.50.2-2000w20k-0704/spec2006/400.perlbench/400.perlbench-llvm-ckpt/400.perlbench-20250705-47578.json
description = test_case_2

[TEST_CASE_3]
command = path_to_gfsim/gfsim -m 10 -s core.soc_enable=true core.bp_mode=0 core.perfect_load_store=false -s core.simtEnable=false -f /remote/lms06/modelci/jenkins/workspace/files_root/benchmark_ckpt/pkgs/ckpt-v0.50.2-2000w20k-0704.zip.d/ckpt-v0.50.2-2000w20k-0704/spec2006/400.perlbench/400.perlbench-llvm-ckpt/400.perlbench-20250705-51323.json
description = test_case_3