#pragma once

#include <cstdint>
#include <iostream>
#include <vector>

#include "bctrl/bctrl_stats.h"
#include "bctrl/spe/CodeTemplate.h"
#include "bctrl/spe/Decoder.h"
#include "core/Bus.h"
#include "ModelSpec.h"
#include "ModelCommon/SimInstInfo.h"

namespace JCore {

class SPE;
struct SbarState {
    bool                    sbar_vld = false;
    SpecType                spec_type;
    uint64_t                store_count = 0;
    uint64_t                addr_base;
    ROBID                   bid;
};

struct StatsInfo {
    uint64_t               allocROBCnt = 0; // the number of pe_rob entry allocated per cycles
    uint64_t               allocROBTotalCnt = 0;
    uint64_t               slotsTotal = 0;
    uint64_t               receiveInstCnt = 0; // the total number of minsts received from bcc
    uint64_t               receiveHdrCnt = 0; // the total number of header received from bcc
    uint64_t               receiveCTHdrCnt = 0; // the total number of CT header received from bcc
    // the total number of minsts that are generated by CT and sent to the DCtop to be allocated rob entry
    uint64_t               genCTInstCnt = 0;
    // the total number of minsts that are decoded and sent to the DCtop to be allocated rob entry
    uint64_t               decodeInstCnt = 0;
    uint64_t               renameBubble = 0; // the bandwidth loss due to rename stall per cycles
    // the bandwidth loss caused by insufficient minsts sent by the Decoder per cycles
    uint64_t               supplyBubble = 0;
    bool                   decoderStall = false;
    bool                   codeTemplateStall = false;

    void Reset()
    {
        allocROBCnt = 0;
        renameBubble = 0;
        supplyBubble = 0;
    }
};

class DCTop : public SimObj {
private:
    // Use dispetch queue
    std::vector<BHeader>            lastHeader;

public:
    SimSys                          *sim;
    std::vector<std::vector<SimInst>> stallInstArr;
    std::vector<bool>               readFile;
    std::vector<bool>               waitMcopy;
    std::vector<uint64_t>           loadCount;
    std::vector<uint64_t>           storeCount;
    std::vector<uint64_t>           mtcLoadCount;
    std::vector<uint64_t>           mtcStoreCount;
    SbarState                       storeInfo;

    std::vector<Decoder>            decoderDev;
    std::vector<CodeTemplate>       templateDev;

    std::vector<std::vector<uint64_t>>           regData;
    LocalRegMgr                     tileRegMgr;
    SPE                             *top;
    /* \brief Record statistics in decoder */
    std::vector<StatsInfo>           statsInfo;

    /* OUTPUT */
    std::vector<std::deque<SimInst>> inst_top_dec_arr;
    std::vector<std::deque<SimInst>> inst_top_ct_arr;

    /* INPUT */
    std::vector<std::vector<std::deque<SimInst>>> blockSplitDCTopArr;
    std::vector<std::deque<SimInst>> inst_dc_top_arr;
    std::vector<std::deque<SimInst>> inst_ct_top_arr;
    SimQueue<SimInst> *dec_ren_q;

    void                            SetLastHeader(BHeader &header);
    SimInst                         SelectbyInstQ(uint32_t peid, std::deque<SimInst> &instQ,
                                        std::deque<SimInst>::const_iterator it,
                                        ROBID &oldestBid, BlockCommandPtr &cmd);
    SimInst                         SelectByStid(uint32_t peid, uint32_t stid, ROBID &oldestBid, BlockCommandPtr &cmd);
    SimInst                         SelectInst(uint32_t peid, uint32_t stid);
    void                            SetLoadStoreID(SimInst &inst);
    bool                            checkCTStall(uint32_t stid);
    bool                            checkDCInStall(uint32_t peID, uint32_t inputCnt=1);
    bool                            checkCTInStall(uint32_t peID, uint32_t inputCnt=1);
    bool                            checkPEStall(uint32_t pe);
    bool                            CheckPEStall(uint32_t pe, uint32_t stid);
    void                            calcLSCnt(BHeader &header);
    Opcode                          preDecode(BHeader &header);
    void                            getRefInfo(SimInst &inst, bool needCheck);

    void                            flush(FlushBus &flushReq);
    void                            Reset();
    void                            Work();
    void                            Xfer();
    void                            Build();
    SimSys                          *GetSim();
    void ReportStat() override {}
    void                            RecordDecoderStats();
    void                            RecordRobStall(uint32_t width, uint32_t stid);
    void                            RecordRegStall(uint32_t peid, uint32_t width, uint32_t stid);
    DCTop() {}
    virtual ~DCTop();
};


} // namespace JCore
