#pragma once

#ifndef SCALAR_PE_STATS_H
#define SCALAR_PE_STATS_H

#include <vector>

#include "DataStruct/base_stats.h"

namespace JCore {
class SPEStats : public NS_PLAT::BaseStats {
public:
    virtual ~SPEStats() {}
    // common PMU counters for PE
    uint64_t cycles = 0; // @PE::Work
    uint64_t decodeCycle = 0;
    uint64_t alloc_cycle = 0; // the count of cycle allocated to perob
    uint64_t renameCycle = 0; // the count of cycle rename module performed
    uint64_t d2_s1_cycle = 0; // the count of cycle with minst to enter iq
    uint64_t binsts = 0; // @PE::setBlockComplete
    uint64_t binsts_commit = 0; // @BROB:commitBlock
    uint64_t minsts = 0; // @OPE::rob/IPE::execute/TPE::rob
    uint64_t robDepth = 0;
    uint64_t max_rob_size = 0;
    uint64_t minsts_per_cycle = 0;
    uint64_t exist_minst_cycle = 0;
    /* top-down
     * slots_total = slots_rob_allocated + slots_fe_bubble + slots_idle
     * slots_fe_bubble = slots_frontend_bound + slots_backend_bound
     * slots_fe_bubble = slots_supply_bubble + slotsRobStall + slotsRenameStall
     * slots_supply_bubble = slots_decode_stall + slots_bcc_supply_stall
     * slots_bcc_supply_stall = slots_flush_recover_bubble + slots_bcc_send_bubble
     * slots_frontend_bound = slots_bcc_supply_bubble + Decode bound
     * slots_backend_bound = Rename bound + ROB bound + iex bound
     */
    uint64_t slots_total = 0; // @PE::Work, +retire width each cycle
    uint64_t slots_rob_allocated = 0; // the number of pe_rob entry allocated
    uint64_t slots_fe_bubble = 0; // while(!isPEIdl) slots_fe_bubble += pe_dec_width - allocROBCnt;
    uint64_t slots_idle = 0; // while the pe_rob is empty and no perob entry is allocated
    uint64_t slots_flush_recover_idle = 0; // pe_idle due to flush
    uint64_t slotsReceived = 0; // the total number of minsts、hdr、ct_hdr received from bcc
    // the total number of minsts that are generated by CT and sent to the DCtop to be allocated rob entry
    uint64_t slotsCtGen = 0;
    // the total number of minsts that are decoded and sent to the DCtop to be allocated rob entry
    uint64_t slotsDecoderSend = 0;
    uint64_t slots_supply_bubble = 0; // the bandwidth loss caused by insufficient minsts sent by the Decoder
    uint64_t slots_decode_stall = 0; // the bandwidth loss due to decoder stall and CT stall
    uint64_t slots_flush_recover_bubble = 0; // the bandwidth loss due to flush
    uint32_t slotsRenameStall = 0; // the bandwidth loss due to rename stall；= freelistStall + localRegStall
    uint64_t slotsRobStall = 0; // the bandwidth loss due to perob stall
    uint64_t slotsIqStall = 0; // the bandwidth loss due to iq stall

    uint64_t exec_stall = 0; // num of cycles when few insts have executed
    uint64_t memstall_anyload = 0; // cycles when exec is stalled and anyload is not completed
    uint64_t memstall_store = 0;
    uint64_t memstall_l1miss = 0;
    uint64_t memstall_l2miss = 0;
    uint64_t memstall_mem = 0;
    // minst types
    uint64_t retired_load = 0;
    uint64_t retired_store = 0;
    uint64_t retired_innerJump = 0;
    // core bound breakdown
    uint64_t curr_cycle_issued_cnt = 0;
    uint64_t stall_get = 0; // no uop issued, any waiting get
    uint64_t stall_get_or_load = 0; // no uop issued, any waiting get or inflight load

    uint64_t s1_inst_cnt = 0; // S1 inst count
    uint64_t d2_optimized_inst = 0;
    uint64_t d2_s1_inst = 0;
    uint64_t d2_reg_sink_inst = 0;
    uint32_t decode_cnt = 0;

    uint64_t localRegStall = 0;
    uint64_t robStall = 0;
    uint64_t threadRobStall[4] = {0};
    uint64_t threadPickCnt[4] = {0};

    uint64_t vecTotalRobBussyCyc = 1;
    uint64_t vecTotalRobBussyInstNum = 0;
    std::vector<uint64_t> vecThreadRobBussyCyc;
    std::vector<uint64_t> vecThreadRobBussyInstNum;

    uint64_t ibStall = 0;
    uint64_t pptagStall = 0;
    uint64_t vptagStall = 0;
    uint64_t lptagStall = 0;

    std::vector<uint64_t> mapQStall;
    std::vector<uint64_t> logicROBStall;

    std::vector<uint64_t> vrfUsedCycles;
    std::vector<uint64_t> vrfUsedTimes;
    std::vector<uint64_t> vrfRecycledTimes;
    std::vector<uint64_t> vrfPreReleaseTimes;

    uint64_t retiredScalar = 0;
    uint64_t retiredVector = 0;
    uint64_t retiredGather = 0;
    uint64_t retiredScatter = 0;
    uint64_t retiredDivSqrt = 0;

    uint64_t sAluInstsCycles = 0;
    uint64_t sLoadInstsCycles = 0;
    uint64_t sStoreInstsCycles = 0;
    uint64_t vAluInstsCycles = 0;
    uint64_t vLoadInstsCycles = 0;
    uint64_t vStoreInstsCycles = 0;

    uint64_t retiredAluInst = 0;
    uint64_t retiredSAluInst = 0;
    uint64_t retiredVAluInst = 0;
    uint64_t retiredLoadInst = 0;
    uint64_t retiredStoreInst = 0;

    using BaseStats::BaseStats;
    using BaseStats::Reset;
    using BaseStats::report;

    virtual void report(std::string& pe_name);
    virtual void ReportVec(const std::string& name = "");
    virtual void topdown(std::string& pe_name);
    virtual void Reset();
};
}
#endif
